### PR TITLE
Added article about Swift scripting.

### PR DESCRIPTION
**Pull request by bontoJR**

### CODE REVIEW

**Comment by bontoJR** [comment]
@marmelroy @JohnSundell 

the plan is to do the release on Monday, any news on this, we can definitely make this happen on the next issue if necessary ;)

**Comment by JohnSundell** [comment]
@marmelroy @bontoJR If possible, let's postpone to the next release 👍 That way we have more time to do a really good post, rather than rush something 😄 I was planning to get this done sooner, but you know, travel & life 😅 But me and @marmelroy have discussed some ideas for the article, and we just need to sit down now and get everything together. When is the next release @bontoJR?

**Comment by bontoJR** [comment]
Absolutely no problems. :)
Next release is in July, starting ever 2 months, as soon as the project gains (hopefully) the right traction, we will switch to a monthly release. :)

**Comment by bontoJR** [comment]
Moved to next release.

**Pull request closed without merging**
